;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        handle-switch-frame
        helm-occur
        helm-show-kill-ring
        helpful-variable
        indent-for-tab-command
        lsp-ui-doc--handle-mouse-movement
        lw-backword-kill-word-dwim
        lw-flex
        lw-python-send-or-projectile
        lw-sp-strict-delete-char-unless-string
        sp-backward-sexp
        sp-backward-up-sexp
        sp-beginning-of-sexp
        sp-down-sexp
        sp-end-of-sexp
        sp-forward-sexp
        sp-kill-word
        sp-transpose-sexp
        sp-unwrap-sexp
        sp-up-sexp
        string-inflection-all-cycle
        whole-line-or-region-kill-region
        sp-forward-slurp-sexp
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        embark-bindings
        multiple-cursors-mode
        ))
